
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Georgia Tech Elba Project
email: elba@cc.gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Georgia Tech Elba Project page contains a tutorial for how to install and deploy Project Elba's tools for conducting large scale system experiments
  Our tooling currently supports public cloud infastructures like PRObe and Emulab.
  We plan to support other infastructures like NSF Cloud and Chameleon in the coming months 
#baseurl: https://coc-gatech-newelba.github.io # the subpath of your site, e.g. /blog
url: https://coc-gatech-newelba.github.io # the base hostname & protocol for your site, e.g. http://example.com
GT Elba Research: https://www.cc.gatech.edu/systems/projects/Elba/index.html
#github_username: --
#permalink: /:name

# Build settings
name: coc-gatech-newelba.github.io
markdown: kramdown
theme: minima
#theme: jekyll-theme-slate
#plugins:
#  - jekyll-feed

header_pages:
  - about.md
  - /blog/index.md
permalink: /blog/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
